# This file can be used to customize the files managed by PDK.
#
# See https://github.com/danielparks/pdk-templates/blob/main/README.md
# for more information.
#
# See https://github.com/danielparks/pdk-templates/blob/main/config_defaults.yml
# for the default values.
---
# Files not to include in the release package
.pdkignore:
  paths:
    - /fix-reference.rb

.github/workflows/pr-checks.yaml:
  validate-REFERENCE.md: false

release.rb:
  validate-REFERENCE.md: false
