# This file can be used to customize the files managed by PDK.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/README.md
# for more information.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/config_defaults.yml
# for the default values.
---
.pdkignore:
  paths:
    - /test.sh
    - /util.sh
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
      - gem: 'puppet_litmus'
        git: 'https://github.com/puppetlabs/puppet_litmus'
        ref: 'main'
spec/spec_helper.rb:
  mock_with: ':rspec'
.rubocop.yml:
  default_configs:
    # Guard clauses are sometimes ambigious, and often harder to read.
    Style/GuardClause:
      Enabled: false
    # Using next instead of if often makes things harder to read.
    Style/Next:
      Enabled: false
